spring:
  application:
    name: 'finance'
  datasource:
    url: jdbc:postgresql://localhost:5432/finance # A porta permanece a mesma
    username: asdf
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080

finance:
  security:
    secret: "segredo_secreto"
