spring:
  profiles:
    active: DEV
  application:
    name: 'finance'
  datasource:
    url: jdbc:postgresql://localhost:5432/finance # A porta permanece a mesma
    username: asdf
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
  redis:
    host: redis
    port: 6379
server:
  port: 8080
